# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: embertech.io
title: Ember Tech
email: embertech.io@gmail.com
author: Erin
description: > # Bringing media rich formatting to a screen near you.
copyright: 'Copyright &copy; 2016 Ember Technologies. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: e-mail
    url: mailto:embertech.io@gmail.com

